 id | owner_id |                                                                                                                                                                                                                description                                                                                                                                                                                                                 |            title             |    category    
----+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------+----------------
  1 |        9 | Hello! My name is Artur, it’s a pleasure to meet you. I have a background in Business Analytics with just over 10 years experience creating data-driven solutions for various business problems. Specifically, I love and have had great success in the strategic evaluation of data analysis with our executive staff. It sounds like you do similar work—I would love to keep in touch to learn more about what you and your company do. | Analyst                      | interviewpitch
  2 |        9 | Hello! My name is Amwata, it’s a pleasure to meet you. I have a background in Business Analytics with just over 10 years experience creating data-driven solutions for various business problems. Specifically, I love and have had great success in the strategic evaluation of data analysis with our executive staff. It sounds like you do similar work—I would love to keep in touch to learn more about what you and your company do. | Analyst                      | interviewpitch
  3 |        1 | Is your name Wi-Fi? Because I'm feeling a connection.                                                                                                                                                                                                                                                                                                                                                                                      | Cheesy                       | pickuplines
  4 |        1 | I want to architect and launch the pink web. Everyone has heard of the dark web, this is it's feminine alter ego. The Pink Web will cater to the female audience. It will be an online place for girls and woman to share, contemplate, shop, chat, and plan virtual and concrete girl centric things.                                                                                                                                     | The Pink Web                 | productpitch
  5 |        1 | I make panties out of Avocados. I want to turn it into a full-fledged business to combat fast fashion, save the environment and empower women.                                                                                                                                                                                                                                                                                             | Panties made out of avocados | productpitch
  6 |        1 | Takes care of your plant when you're away from home, uses IOT(internet of things) and lets users connect to an app to stay in touch with their plants conditions at all times ensuring optimum growth.                                                                                                                                                                                                                                     | Automatic garden             | productpitch
(6 rows)

